name: Generate PDF with asciidoctor
run-name: ${{ github.actor }} is creating the pdf document

on:
  push:
    branches:
    - main


jobs:
  Install-asciidoctor:

    # Set the job to run on Ubuntu
    runs-on: ubuntu-latest

    # Set up the job environment
    steps:

      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      # Install asciidoctor
      - run: gem install asciidoctor

      # Install asciidoctor-pdf
      - run: gem install asciidoctor-pdf

      # Generate the PDF
      - run: asciidoctor-pdf --theme my-theme.yml BOOK.adoc -o PYTHON_BIBLE.pdf