name: Generate PDF with asciidoctor
run-name: ${{ github.actor }} is creating the pdf document

on:
  push:
    branches:
    - main


jobs:
  Generate-PDF-file:

    # Set the job to run on Ubuntu
    runs-on: ubuntu-latest

    # Set up the job environment
    steps:

      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up git user name and email to match the committer
      - name: Setup git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      # Set up Ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      # Install asciidoctor
      - run: gem install asciidoctor

      # Install asciidoctor-pdf
      - run: gem install asciidoctor-pdf

      # Generate the PDF
      - run: asciidoctor-pdf --theme ./Assets/pdf/themes/my-theme.yml BOOK.adoc -o ./Build/AWESOME_PYTHON.pdf

      # Commit the PDF file
      - name: Commit files
        run: |
          git add .
          git commit -m "${{ github.actor }} published the pdf document"
          git push
